// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/crypto/security_keys.proto

package crypto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedPrivateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          []byte                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,3,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedPrivateKey) Reset() {
	*x = EncryptedPrivateKey{}
	mi := &file_internal_crypto_security_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPrivateKey) ProtoMessage() {}

func (x *EncryptedPrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_crypto_security_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPrivateKey.ProtoReflect.Descriptor instead.
func (*EncryptedPrivateKey) Descriptor() ([]byte, []int) {
	return file_internal_crypto_security_keys_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedPrivateKey) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptedPrivateKey) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedPrivateKey) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *EncryptedPrivateKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

var File_internal_crypto_security_keys_proto protoreflect.FileDescriptor

const file_internal_crypto_security_keys_proto_rawDesc = "" +
	"\n" +
	"#internal/crypto/security_keys.proto\x12\x06crypto\"\x82\x01\n" +
	"\x13EncryptedPrivateKey\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12#\n" +
	"\rencrypted_key\x18\x03 \x01(\fR\fencryptedKey\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithmB?Z=github.com/DmytroBuzhylov/P2PMessenger/internal/crypto;cryptob\x06proto3"

var (
	file_internal_crypto_security_keys_proto_rawDescOnce sync.Once
	file_internal_crypto_security_keys_proto_rawDescData []byte
)

func file_internal_crypto_security_keys_proto_rawDescGZIP() []byte {
	file_internal_crypto_security_keys_proto_rawDescOnce.Do(func() {
		file_internal_crypto_security_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_crypto_security_keys_proto_rawDesc), len(file_internal_crypto_security_keys_proto_rawDesc)))
	})
	return file_internal_crypto_security_keys_proto_rawDescData
}

var file_internal_crypto_security_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_crypto_security_keys_proto_goTypes = []any{
	(*EncryptedPrivateKey)(nil), // 0: crypto.EncryptedPrivateKey
}
var file_internal_crypto_security_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_crypto_security_keys_proto_init() }
func file_internal_crypto_security_keys_proto_init() {
	if File_internal_crypto_security_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_crypto_security_keys_proto_rawDesc), len(file_internal_crypto_security_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_crypto_security_keys_proto_goTypes,
		DependencyIndexes: file_internal_crypto_security_keys_proto_depIdxs,
		MessageInfos:      file_internal_crypto_security_keys_proto_msgTypes,
	}.Build()
	File_internal_crypto_security_keys_proto = out.File
	file_internal_crypto_security_keys_proto_goTypes = nil
	file_internal_crypto_security_keys_proto_depIdxs = nil
}
