// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/proto/message.proto

package internal_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_internal_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type MessageData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	OriginId  []byte                 `protobuf:"bytes,2,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	TargetId  []byte                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Timestamp uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HopLimit  uint32                 `protobuf:"varint,5,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MessageData_HandshakeInit
	//	*MessageData_Ping
	//	*MessageData_Ack
	//	*MessageData_ChatMessage
	//	*MessageData_PeerList
	//	*MessageData_Transfer
	//	*MessageData_HandshakeResponse
	//	*MessageData_PeerReq
	//	*MessageData_PeerRes
	Payload       isMessageData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_internal_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageData) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageData) GetOriginId() []byte {
	if x != nil {
		return x.OriginId
	}
	return nil
}

func (x *MessageData) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *MessageData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageData) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *MessageData) GetPayload() isMessageData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageData) GetHandshakeInit() *HandshakeInit {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_HandshakeInit); ok {
			return x.HandshakeInit
		}
	}
	return nil
}

func (x *MessageData) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MessageData) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MessageData) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *MessageData) GetPeerList() *PeerList {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_PeerList); ok {
			return x.PeerList
		}
	}
	return nil
}

func (x *MessageData) GetTransfer() *Transaction {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *MessageData) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *MessageData) GetPeerReq() *PeerRequest {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_PeerReq); ok {
			return x.PeerReq
		}
	}
	return nil
}

func (x *MessageData) GetPeerRes() *PeerResponse {
	if x != nil {
		if x, ok := x.Payload.(*MessageData_PeerRes); ok {
			return x.PeerRes
		}
	}
	return nil
}

type isMessageData_Payload interface {
	isMessageData_Payload()
}

type MessageData_HandshakeInit struct {
	HandshakeInit *HandshakeInit `protobuf:"bytes,6,opt,name=handshake_init,json=handshakeInit,proto3,oneof"`
}

type MessageData_Ping struct {
	Ping *Ping `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

type MessageData_Ack struct {
	Ack *Ack `protobuf:"bytes,8,opt,name=ack,proto3,oneof"`
}

type MessageData_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,9,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type MessageData_PeerList struct {
	PeerList *PeerList `protobuf:"bytes,10,opt,name=peer_list,json=peerList,proto3,oneof"`
}

type MessageData_Transfer struct {
	Transfer *Transaction `protobuf:"bytes,11,opt,name=transfer,proto3,oneof"`
}

type MessageData_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,12,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type MessageData_PeerReq struct {
	PeerReq *PeerRequest `protobuf:"bytes,13,opt,name=peer_req,json=peerReq,proto3,oneof"`
}

type MessageData_PeerRes struct {
	PeerRes *PeerResponse `protobuf:"bytes,14,opt,name=peer_res,json=peerRes,proto3,oneof"`
}

func (*MessageData_HandshakeInit) isMessageData_Payload() {}

func (*MessageData_Ping) isMessageData_Payload() {}

func (*MessageData_Ack) isMessageData_Payload() {}

func (*MessageData_ChatMessage) isMessageData_Payload() {}

func (*MessageData_PeerList) isMessageData_Payload() {}

func (*MessageData_Transfer) isMessageData_Payload() {}

func (*MessageData_HandshakeResponse) isMessageData_Payload() {}

func (*MessageData_PeerReq) isMessageData_Payload() {}

func (*MessageData_PeerRes) isMessageData_Payload() {}

type ChatMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedPayload []byte                 `protobuf:"bytes,1,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo          string                 `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type HandshakeInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeInit) Reset() {
	*x = HandshakeInit{}
	mi := &file_internal_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeInit) ProtoMessage() {}

func (x *HandshakeInit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeInit.ProtoReflect.Descriptor instead.
func (*HandshakeInit) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeInit) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeResponse) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *HandshakeResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerList_Peer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_internal_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *PeerList) GetPeers() []*PeerList_Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefMessageId  string                 `protobuf:"bytes,1,opt,name=ref_message_id,json=refMessageId,proto3" json:"ref_message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetRefMessageId() string {
	if x != nil {
		return x.RefMessageId
	}
	return ""
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_internal_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *PeerInfo) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_internal_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *PeerRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	mi := &file_internal_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *PeerResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerList_Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastKnownAddr string                 `protobuf:"bytes,2,opt,name=last_known_addr,json=lastKnownAddr,proto3" json:"last_known_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList_Peer) Reset() {
	*x = PeerList_Peer{}
	mi := &file_internal_proto_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList_Peer) ProtoMessage() {}

func (x *PeerList_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList_Peer.ProtoReflect.Descriptor instead.
func (*PeerList_Peer) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PeerList_Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerList_Peer) GetLastKnownAddr() string {
	if x != nil {
		return x.LastKnownAddr
	}
	return ""
}

var File_internal_proto_message_proto protoreflect.FileDescriptor

const file_internal_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/message.proto\x12\x03p2p\"U\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x17\n" +
	"\apub_key\x18\x03 \x01(\fR\x06pubKey\"\xe5\x04\n" +
	"\vMessageData\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\torigin_id\x18\x02 \x01(\fR\boriginId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\fR\btargetId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\thop_limit\x18\x05 \x01(\rR\bhopLimit\x12;\n" +
	"\x0ehandshake_init\x18\x06 \x01(\v2\x12.p2p.HandshakeInitH\x00R\rhandshakeInit\x12\x1f\n" +
	"\x04ping\x18\a \x01(\v2\t.p2p.PingH\x00R\x04ping\x12\x1c\n" +
	"\x03ack\x18\b \x01(\v2\b.p2p.AckH\x00R\x03ack\x125\n" +
	"\fchat_message\x18\t \x01(\v2\x10.p2p.ChatMessageH\x00R\vchatMessage\x12,\n" +
	"\tpeer_list\x18\n" +
	" \x01(\v2\r.p2p.PeerListH\x00R\bpeerList\x12.\n" +
	"\btransfer\x18\v \x01(\v2\x10.p2p.TransactionH\x00R\btransfer\x12G\n" +
	"\x12handshake_response\x18\f \x01(\v2\x16.p2p.HandshakeResponseH\x00R\x11handshakeResponse\x12-\n" +
	"\bpeer_req\x18\r \x01(\v2\x10.p2p.PeerRequestH\x00R\apeerReq\x12.\n" +
	"\bpeer_res\x18\x0e \x01(\v2\x11.p2p.PeerResponseH\x00R\apeerResB\t\n" +
	"\apayload\":\n" +
	"\vChatMessage\x12+\n" +
	"\x11encrypted_payload\x18\x01 \x01(\fR\x10encryptedPayload\"T\n" +
	"\vTransaction\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04memo\x18\x03 \x01(\tR\x04memo\"%\n" +
	"\rHandshakeInit\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"d\n" +
	"\x11HandshakeResponse\x12\x17\n" +
	"\apub_key\x18\x01 \x01(\fR\x06pubKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"t\n" +
	"\bPeerList\x12(\n" +
	"\x05peers\x18\x01 \x03(\v2\x12.p2p.PeerList.PeerR\x05peers\x1a>\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0flast_known_addr\x18\x02 \x01(\tR\rlastKnownAddr\"+\n" +
	"\x03Ack\x12$\n" +
	"\x0eref_message_id\x18\x01 \x01(\tR\frefMessageId\"=\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apub_key\x18\x01 \x01(\fR\x06pubKey\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"#\n" +
	"\vPeerRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"3\n" +
	"\fPeerResponse\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.p2p.PeerInfoR\x05peersBCZAgithub.com/DmytroBuzhylov/P2PMessenger/internal/proto;internal_pbb\x06proto3"

var (
	file_internal_proto_message_proto_rawDescOnce sync.Once
	file_internal_proto_message_proto_rawDescData []byte
)

func file_internal_proto_message_proto_rawDescGZIP() []byte {
	file_internal_proto_message_proto_rawDescOnce.Do(func() {
		file_internal_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_message_proto_rawDesc), len(file_internal_proto_message_proto_rawDesc)))
	})
	return file_internal_proto_message_proto_rawDescData
}

var file_internal_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_message_proto_goTypes = []any{
	(*Envelope)(nil),          // 0: p2p.Envelope
	(*MessageData)(nil),       // 1: p2p.MessageData
	(*ChatMessage)(nil),       // 2: p2p.ChatMessage
	(*Transaction)(nil),       // 3: p2p.Transaction
	(*HandshakeInit)(nil),     // 4: p2p.HandshakeInit
	(*HandshakeResponse)(nil), // 5: p2p.HandshakeResponse
	(*Ping)(nil),              // 6: p2p.Ping
	(*PeerList)(nil),          // 7: p2p.PeerList
	(*Ack)(nil),               // 8: p2p.Ack
	(*PeerInfo)(nil),          // 9: p2p.PeerInfo
	(*PeerRequest)(nil),       // 10: p2p.PeerRequest
	(*PeerResponse)(nil),      // 11: p2p.PeerResponse
	(*PeerList_Peer)(nil),     // 12: p2p.PeerList.Peer
}
var file_internal_proto_message_proto_depIdxs = []int32{
	4,  // 0: p2p.MessageData.handshake_init:type_name -> p2p.HandshakeInit
	6,  // 1: p2p.MessageData.ping:type_name -> p2p.Ping
	8,  // 2: p2p.MessageData.ack:type_name -> p2p.Ack
	2,  // 3: p2p.MessageData.chat_message:type_name -> p2p.ChatMessage
	7,  // 4: p2p.MessageData.peer_list:type_name -> p2p.PeerList
	3,  // 5: p2p.MessageData.transfer:type_name -> p2p.Transaction
	5,  // 6: p2p.MessageData.handshake_response:type_name -> p2p.HandshakeResponse
	10, // 7: p2p.MessageData.peer_req:type_name -> p2p.PeerRequest
	11, // 8: p2p.MessageData.peer_res:type_name -> p2p.PeerResponse
	12, // 9: p2p.PeerList.peers:type_name -> p2p.PeerList.Peer
	9,  // 10: p2p.PeerResponse.peers:type_name -> p2p.PeerInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_proto_message_proto_init() }
func file_internal_proto_message_proto_init() {
	if File_internal_proto_message_proto != nil {
		return
	}
	file_internal_proto_message_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageData_HandshakeInit)(nil),
		(*MessageData_Ping)(nil),
		(*MessageData_Ack)(nil),
		(*MessageData_ChatMessage)(nil),
		(*MessageData_PeerList)(nil),
		(*MessageData_Transfer)(nil),
		(*MessageData_HandshakeResponse)(nil),
		(*MessageData_PeerReq)(nil),
		(*MessageData_PeerRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_message_proto_rawDesc), len(file_internal_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_message_proto_goTypes,
		DependencyIndexes: file_internal_proto_message_proto_depIdxs,
		MessageInfos:      file_internal_proto_message_proto_msgTypes,
	}.Build()
	File_internal_proto_message_proto = out.File
	file_internal_proto_message_proto_goTypes = nil
	file_internal_proto_message_proto_depIdxs = nil
}
