// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/storage/types.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerStoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	LastKnownAddr string                 `protobuf:"bytes,2,opt,name=last_known_addr,json=lastKnownAddr,proto3" json:"last_known_addr,omitempty"`
	LastSeen      uint64                 `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	TrustScore    uint32                 `protobuf:"varint,4,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStoreEntry) Reset() {
	*x = PeerStoreEntry{}
	mi := &file_internal_storage_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStoreEntry) ProtoMessage() {}

func (x *PeerStoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStoreEntry.ProtoReflect.Descriptor instead.
func (*PeerStoreEntry) Descriptor() ([]byte, []int) {
	return file_internal_storage_types_proto_rawDescGZIP(), []int{0}
}

func (x *PeerStoreEntry) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *PeerStoreEntry) GetLastKnownAddr() string {
	if x != nil {
		return x.LastKnownAddr
	}
	return ""
}

func (x *PeerStoreEntry) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerStoreEntry) GetTrustScore() uint32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

var File_internal_storage_types_proto protoreflect.FileDescriptor

const file_internal_storage_types_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/storage/types.proto\x12\astorage\"\x8f\x01\n" +
	"\x0ePeerStoreEntry\x12\x17\n" +
	"\apub_key\x18\x01 \x01(\fR\x06pubKey\x12&\n" +
	"\x0flast_known_addr\x18\x02 \x01(\tR\rlastKnownAddr\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x04R\blastSeen\x12\x1f\n" +
	"\vtrust_score\x18\x04 \x01(\rR\n" +
	"trustScoreBAZ?github.com/DmytroBuzhylov/P2PMessenger/internal/storage;storageb\x06proto3"

var (
	file_internal_storage_types_proto_rawDescOnce sync.Once
	file_internal_storage_types_proto_rawDescData []byte
)

func file_internal_storage_types_proto_rawDescGZIP() []byte {
	file_internal_storage_types_proto_rawDescOnce.Do(func() {
		file_internal_storage_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_storage_types_proto_rawDesc), len(file_internal_storage_types_proto_rawDesc)))
	})
	return file_internal_storage_types_proto_rawDescData
}

var file_internal_storage_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_storage_types_proto_goTypes = []any{
	(*PeerStoreEntry)(nil), // 0: storage.PeerStoreEntry
}
var file_internal_storage_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_storage_types_proto_init() }
func file_internal_storage_types_proto_init() {
	if File_internal_storage_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_storage_types_proto_rawDesc), len(file_internal_storage_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_storage_types_proto_goTypes,
		DependencyIndexes: file_internal_storage_types_proto_depIdxs,
		MessageInfos:      file_internal_storage_types_proto_msgTypes,
	}.Build()
	File_internal_storage_types_proto = out.File
	file_internal_storage_types_proto_goTypes = nil
	file_internal_storage_types_proto_depIdxs = nil
}
