// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/proto/content.proto

package api_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ContentMessage_InitReq
	//	*ContentMessage_InitRes
	//	*ContentMessage_ChunkReq
	//	*ContentMessage_ChunkRes
	Payload       isContentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentMessage) Reset() {
	*x = ContentMessage{}
	mi := &file_pkg_api_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentMessage) ProtoMessage() {}

func (x *ContentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentMessage.ProtoReflect.Descriptor instead.
func (*ContentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentMessage) GetPayload() isContentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ContentMessage) GetInitReq() *SessionInitRequest {
	if x != nil {
		if x, ok := x.Payload.(*ContentMessage_InitReq); ok {
			return x.InitReq
		}
	}
	return nil
}

func (x *ContentMessage) GetInitRes() *SessionInitResponse {
	if x != nil {
		if x, ok := x.Payload.(*ContentMessage_InitRes); ok {
			return x.InitRes
		}
	}
	return nil
}

func (x *ContentMessage) GetChunkReq() *ChunkRequest {
	if x != nil {
		if x, ok := x.Payload.(*ContentMessage_ChunkReq); ok {
			return x.ChunkReq
		}
	}
	return nil
}

func (x *ContentMessage) GetChunkRes() *ChunkResponse {
	if x != nil {
		if x, ok := x.Payload.(*ContentMessage_ChunkRes); ok {
			return x.ChunkRes
		}
	}
	return nil
}

type isContentMessage_Payload interface {
	isContentMessage_Payload()
}

type ContentMessage_InitReq struct {
	InitReq *SessionInitRequest `protobuf:"bytes,1,opt,name=init_req,json=initReq,proto3,oneof"`
}

type ContentMessage_InitRes struct {
	InitRes *SessionInitResponse `protobuf:"bytes,2,opt,name=init_res,json=initRes,proto3,oneof"`
}

type ContentMessage_ChunkReq struct {
	ChunkReq *ChunkRequest `protobuf:"bytes,3,opt,name=chunk_req,json=chunkReq,proto3,oneof"`
}

type ContentMessage_ChunkRes struct {
	ChunkRes *ChunkResponse `protobuf:"bytes,4,opt,name=chunk_res,json=chunkRes,proto3,oneof"`
}

func (*ContentMessage_InitReq) isContentMessage_Payload() {}

func (*ContentMessage_InitRes) isContentMessage_Payload() {}

func (*ContentMessage_ChunkReq) isContentMessage_Payload() {}

func (*ContentMessage_ChunkRes) isContentMessage_Payload() {}

type SessionInitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootHash        []byte                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	DesiredStreams  uint32                 `protobuf:"varint,2,opt,name=desired_streams,json=desiredStreams,proto3" json:"desired_streams,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInitRequest) Reset() {
	*x = SessionInitRequest{}
	mi := &file_pkg_api_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInitRequest) ProtoMessage() {}

func (x *SessionInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInitRequest.ProtoReflect.Descriptor instead.
func (*SessionInitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInitRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *SessionInitRequest) GetDesiredStreams() uint32 {
	if x != nil {
		return x.DesiredStreams
	}
	return 0
}

func (x *SessionInitRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type SessionInitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AllowedStreams uint32                 `protobuf:"varint,2,opt,name=allowed_streams,json=allowedStreams,proto3" json:"allowed_streams,omitempty"`
	FileSize       uint64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	SessionId      []byte                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInitResponse) Reset() {
	*x = SessionInitResponse{}
	mi := &file_pkg_api_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInitResponse) ProtoMessage() {}

func (x *SessionInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInitResponse.ProtoReflect.Descriptor instead.
func (*SessionInitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInitResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionInitResponse) GetAllowedStreams() uint32 {
	if x != nil {
		return x.AllowedStreams
	}
	return 0
}

func (x *SessionInitResponse) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SessionInitResponse) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkHash     []byte                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_pkg_api_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ChunkRequest) GetChunkHash() []byte {
	if x != nil {
		return x.ChunkHash
	}
	return nil
}

type ChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_pkg_api_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_pkg_api_proto_content_proto protoreflect.FileDescriptor

const file_pkg_api_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/proto/content.proto\x12\x06api_pb\"\xf9\x01\n" +
	"\x0eContentMessage\x127\n" +
	"\binit_req\x18\x01 \x01(\v2\x1a.api_pb.SessionInitRequestH\x00R\ainitReq\x128\n" +
	"\binit_res\x18\x02 \x01(\v2\x1b.api_pb.SessionInitResponseH\x00R\ainitRes\x123\n" +
	"\tchunk_req\x18\x03 \x01(\v2\x14.api_pb.ChunkRequestH\x00R\bchunkReq\x124\n" +
	"\tchunk_res\x18\x04 \x01(\v2\x15.api_pb.ChunkResponseH\x00R\bchunkResB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\x12SessionInitRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\x12'\n" +
	"\x0fdesired_streams\x18\x02 \x01(\rR\x0edesiredStreams\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\"\x96\x01\n" +
	"\x13SessionInitResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12'\n" +
	"\x0fallowed_streams\x18\x02 \x01(\rR\x0eallowedStreams\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x04R\bfileSize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\fR\tsessionId\"L\n" +
	"\fChunkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\fR\tchunkHash\"9\n" +
	"\rChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05foundB9Z7github.com/DmytroBuzhylov/echofog-core/api/proto;api_pbb\x06proto3"

var (
	file_pkg_api_proto_content_proto_rawDescOnce sync.Once
	file_pkg_api_proto_content_proto_rawDescData []byte
)

func file_pkg_api_proto_content_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_content_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_content_proto_rawDesc), len(file_pkg_api_proto_content_proto_rawDesc)))
	})
	return file_pkg_api_proto_content_proto_rawDescData
}

var file_pkg_api_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_proto_content_proto_goTypes = []any{
	(*ContentMessage)(nil),      // 0: api_pb.ContentMessage
	(*SessionInitRequest)(nil),  // 1: api_pb.SessionInitRequest
	(*SessionInitResponse)(nil), // 2: api_pb.SessionInitResponse
	(*ChunkRequest)(nil),        // 3: api_pb.ChunkRequest
	(*ChunkResponse)(nil),       // 4: api_pb.ChunkResponse
}
var file_pkg_api_proto_content_proto_depIdxs = []int32{
	1, // 0: api_pb.ContentMessage.init_req:type_name -> api_pb.SessionInitRequest
	2, // 1: api_pb.ContentMessage.init_res:type_name -> api_pb.SessionInitResponse
	3, // 2: api_pb.ContentMessage.chunk_req:type_name -> api_pb.ChunkRequest
	4, // 3: api_pb.ContentMessage.chunk_res:type_name -> api_pb.ChunkResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_content_proto_init() }
func file_pkg_api_proto_content_proto_init() {
	if File_pkg_api_proto_content_proto != nil {
		return
	}
	file_pkg_api_proto_content_proto_msgTypes[0].OneofWrappers = []any{
		(*ContentMessage_InitReq)(nil),
		(*ContentMessage_InitRes)(nil),
		(*ContentMessage_ChunkReq)(nil),
		(*ContentMessage_ChunkRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_content_proto_rawDesc), len(file_pkg_api_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_proto_content_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_content_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_content_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_content_proto = out.File
	file_pkg_api_proto_content_proto_goTypes = nil
	file_pkg_api_proto_content_proto_depIdxs = nil
}
