// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/p2p/dht/dag/dag.proto

package dag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBNode_DataType int32

const (
	PBNode_Raw       PBNode_DataType = 0
	PBNode_File      PBNode_DataType = 1
	PBNode_Directory PBNode_DataType = 2
	PBNode_Metadata  PBNode_DataType = 3
	PBNode_Symlink   PBNode_DataType = 4
	PBNode_Commit    PBNode_DataType = 5
)

// Enum value maps for PBNode_DataType.
var (
	PBNode_DataType_name = map[int32]string{
		0: "Raw",
		1: "File",
		2: "Directory",
		3: "Metadata",
		4: "Symlink",
		5: "Commit",
	}
	PBNode_DataType_value = map[string]int32{
		"Raw":       0,
		"File":      1,
		"Directory": 2,
		"Metadata":  3,
		"Symlink":   4,
		"Commit":    5,
	}
)

func (x PBNode_DataType) Enum() *PBNode_DataType {
	p := new(PBNode_DataType)
	*p = x
	return p
}

func (x PBNode_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBNode_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_p2p_dht_dag_dag_proto_enumTypes[0].Descriptor()
}

func (PBNode_DataType) Type() protoreflect.EnumType {
	return &file_internal_p2p_dht_dag_dag_proto_enumTypes[0]
}

func (x PBNode_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBNode_DataType.Descriptor instead.
func (PBNode_DataType) EnumDescriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dag_dag_proto_rawDescGZIP(), []int{1, 0}
}

type PBLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tsize         uint64                 `protobuf:"varint,3,opt,name=tsize,proto3" json:"tsize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBLink) Reset() {
	*x = PBLink{}
	mi := &file_internal_p2p_dht_dag_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBLink) ProtoMessage() {}

func (x *PBLink) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_dht_dag_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBLink.ProtoReflect.Descriptor instead.
func (*PBLink) Descriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dag_dag_proto_rawDescGZIP(), []int{0}
}

func (x *PBLink) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *PBLink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBLink) GetTsize() uint64 {
	if x != nil {
		return x.Tsize
	}
	return 0
}

type PBNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PBNode_DataType        `protobuf:"varint,1,opt,name=type,proto3,enum=dag.PBNode_DataType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Links         []*PBLink              `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Filesize      uint64                 `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Blocksizes    []uint64               `protobuf:"varint,5,rep,packed,name=blocksizes,proto3" json:"blocksizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBNode) Reset() {
	*x = PBNode{}
	mi := &file_internal_p2p_dht_dag_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBNode) ProtoMessage() {}

func (x *PBNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_dht_dag_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBNode.ProtoReflect.Descriptor instead.
func (*PBNode) Descriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dag_dag_proto_rawDescGZIP(), []int{1}
}

func (x *PBNode) GetType() PBNode_DataType {
	if x != nil {
		return x.Type
	}
	return PBNode_Raw
}

func (x *PBNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PBNode) GetLinks() []*PBLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *PBNode) GetFilesize() uint64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *PBNode) GetBlocksizes() []uint64 {
	if x != nil {
		return x.Blocksizes
	}
	return nil
}

var File_internal_p2p_dht_dag_dag_proto protoreflect.FileDescriptor

const file_internal_p2p_dht_dag_dag_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/p2p/dht/dag/dag.proto\x12\x03dag\"F\n" +
	"\x06PBLink\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05tsize\x18\x03 \x01(\x04R\x05tsize\"\xfa\x01\n" +
	"\x06PBNode\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.dag.PBNode.DataTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\x05links\x18\x03 \x03(\v2\v.dag.PBLinkR\x05links\x12\x1a\n" +
	"\bfilesize\x18\x04 \x01(\x04R\bfilesize\x12\x1e\n" +
	"\n" +
	"blocksizes\x18\x05 \x03(\x04R\n" +
	"blocksizes\"S\n" +
	"\bDataType\x12\a\n" +
	"\x03Raw\x10\x00\x12\b\n" +
	"\x04File\x10\x01\x12\r\n" +
	"\tDirectory\x10\x02\x12\f\n" +
	"\bMetadata\x10\x03\x12\v\n" +
	"\aSymlink\x10\x04\x12\n" +
	"\n" +
	"\x06Commit\x10\x05BAZ?github.com/DmytroBuzhylov/echofog-core/internal/p2p/dht/dag;dagb\x06proto3"

var (
	file_internal_p2p_dht_dag_dag_proto_rawDescOnce sync.Once
	file_internal_p2p_dht_dag_dag_proto_rawDescData []byte
)

func file_internal_p2p_dht_dag_dag_proto_rawDescGZIP() []byte {
	file_internal_p2p_dht_dag_dag_proto_rawDescOnce.Do(func() {
		file_internal_p2p_dht_dag_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_dht_dag_dag_proto_rawDesc), len(file_internal_p2p_dht_dag_dag_proto_rawDesc)))
	})
	return file_internal_p2p_dht_dag_dag_proto_rawDescData
}

var file_internal_p2p_dht_dag_dag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_p2p_dht_dag_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_p2p_dht_dag_dag_proto_goTypes = []any{
	(PBNode_DataType)(0), // 0: dag.PBNode.DataType
	(*PBLink)(nil),       // 1: dag.PBLink
	(*PBNode)(nil),       // 2: dag.PBNode
}
var file_internal_p2p_dht_dag_dag_proto_depIdxs = []int32{
	0, // 0: dag.PBNode.type:type_name -> dag.PBNode.DataType
	1, // 1: dag.PBNode.links:type_name -> dag.PBLink
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_p2p_dht_dag_dag_proto_init() }
func file_internal_p2p_dht_dag_dag_proto_init() {
	if File_internal_p2p_dht_dag_dag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_dht_dag_dag_proto_rawDesc), len(file_internal_p2p_dht_dag_dag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_p2p_dht_dag_dag_proto_goTypes,
		DependencyIndexes: file_internal_p2p_dht_dag_dag_proto_depIdxs,
		EnumInfos:         file_internal_p2p_dht_dag_dag_proto_enumTypes,
		MessageInfos:      file_internal_p2p_dht_dag_dag_proto_msgTypes,
	}.Build()
	File_internal_p2p_dht_dag_dag_proto = out.File
	file_internal_p2p_dht_dag_dag_proto_goTypes = nil
	file_internal_p2p_dht_dag_dag_proto_depIdxs = nil
}
